#!/usr/bin/env python3
"""
Teamcast PDF Report Generator

Generates a clean PDF summary of qualified leads from leads.json.

Usage:
    python3 scripts/generate_pdf.py --input data/leads.json --output /tmp/report.pdf
    python3 scripts/generate_pdf.py  # uses defaults
"""

import json
import argparse
from datetime import datetime
from pathlib import Path

try:
    from fpdf import FPDF, XPos, YPos
except ImportError:
    import subprocess, sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "fpdf2", "--quiet"])
    from fpdf import FPDF, XPos, YPos


BASE_DIR = Path(__file__).resolve().parent.parent
DEFAULT_INPUT = BASE_DIR / "data" / "leads.json"
DEFAULT_OUTPUT = Path("/tmp/teamcast_report.pdf")

# Column widths (mm) for the qualified leads table — landscape A4
COLS = {
    "rank":    8,
    "name":    38,
    "title":   48,
    "company": 34,
    "score":   14,
    "signal":  40,
}
TOTAL_W = sum(COLS.values())  # 182 mm


class TeamcastPDF(FPDF):
    def __init__(self, run_id: str, date_str: str):
        super().__init__(orientation="L", unit="mm", format="A4")
        self.run_id = run_id
        self.date_str = date_str
        self.set_auto_page_break(auto=True, margin=12)

    def header(self):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(37, 99, 235)
        self.cell(0, 8, "Teamcast Lead Report", new_x=XPos.RIGHT, new_y=YPos.TOP, align="L")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(107, 114, 128)
        self.cell(0, 8, f"Run: {self.run_id}  |  {self.date_str}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="R")
        self.set_draw_color(229, 231, 235)
        self.line(10, self.get_y(), self.w - 10, self.get_y())
        self.ln(3)

    def footer(self):
        self.set_y(-10)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(156, 163, 175)
        self.cell(0, 5, f"Generated by Teamcast Lead Agent  |  Page {self.page_no()}", align="C")


def truncate(text: str, max_chars: int) -> str:
    text = str(text or "")
    # Strip any non-latin-1 characters that would crash fpdf2 with Helvetica
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text if len(text) <= max_chars else text[: max_chars - 1] + "~"


def render_summary(pdf: TeamcastPDF, stats: dict):
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 7, "Run Summary", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(55, 65, 81)
    rows = [
        ("Total sourced",     stats.get("total_sourced", "-")),
        ("After dedup",       stats.get("after_dedup",   "-")),
        ("Qualified (>=6)",   stats.get("qualified",     "-")),
        ("Review queue (4-5)", stats.get("review_queue", "-")),
        ("Discarded",         stats.get("discarded",     "-")),
    ]
    for label, value in rows:
        pdf.cell(55, 6, label + ":", new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(20, 6, str(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 10)
    pdf.ln(4)

    by_source = stats.get("by_source", {})
    if by_source:
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "By Source:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 10)
        for src, count in by_source.items():
            pdf.cell(10, 5, "", new_x=XPos.RIGHT, new_y=YPos.TOP)
            pdf.cell(0, 5, f"- {src}: {count}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)


def render_table_header(pdf: TeamcastPDF):
    pdf.set_fill_color(243, 244, 246)
    pdf.set_text_color(55, 65, 81)
    pdf.set_font("Helvetica", "B", 8)
    pdf.cell(COLS["rank"],    7, "#",       border=1, fill=True, align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(COLS["name"],    7, "Name",    border=1, fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(COLS["title"],   7, "Title",   border=1, fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(COLS["company"], 7, "Company", border=1, fill=True, new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(COLS["score"],   7, "Score",   border=1, fill=True, align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)
    pdf.cell(COLS["signal"],  7, "Signal",  border=1, fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT)


def render_leads_section(pdf: TeamcastPDF, leads: list, title: str, color_rgb: tuple):
    if not leads:
        return
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*color_rgb)
    pdf.cell(0, 7, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(17, 24, 39)
    render_table_header(pdf)

    for i, lead in enumerate(leads, 1):
        contact = lead.get("contact", {})
        company = lead.get("company", {})
        scoring = lead.get("scoring", {})
        signals = lead.get("signals", {})

        name = contact.get("full_name") or "Contact TBD"
        title_str = contact.get("title") or ""
        company_name = company.get("name") or ""
        score = scoring.get("fit_score") or 0
        signal_detail = signals.get("signal_detail") or scoring.get("strongest_signal") or ""

        fill = i % 2 == 0
        if fill:
            pdf.set_fill_color(249, 250, 251)
        else:
            pdf.set_fill_color(255, 255, 255)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(17, 24, 39)

        pdf.cell(COLS["rank"],    6, str(i),                          border="LR", fill=fill, align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(COLS["name"],    6, truncate(name, 28),              border="LR", fill=fill, new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(COLS["title"],   6, truncate(title_str, 38),         border="LR", fill=fill, new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(COLS["company"], 6, truncate(company_name, 22),      border="LR", fill=fill, new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(COLS["score"],   6, f"{score:.1f}/10",               border="LR", fill=fill, align="C", new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(COLS["signal"],  6, truncate(signal_detail, 32),     border="LR", fill=fill, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        # Sub-row: email + LinkedIn
        email = contact.get("email") or ""
        linkedin = contact.get("linkedin_url") or ""
        detail_parts = []
        if email:
            detail_parts.append(f"Email: {email}")
        if linkedin:
            detail_parts.append(f"LinkedIn: {linkedin}")
        if not detail_parts:
            detail_parts.append("Contact: TBD - needs enrichment")

        pdf.set_font("Helvetica", "I", 7)
        pdf.set_text_color(107, 114, 128)
        pdf.cell(COLS["rank"], 5, "", border="LR", fill=fill, new_x=XPos.RIGHT, new_y=YPos.TOP)
        pdf.cell(TOTAL_W - COLS["rank"], 5, truncate("  |  ".join(detail_parts), 90),
                 border="LR", fill=fill, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Close table
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(TOTAL_W, 0, "", border="T", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)


def render_review_queue(pdf: TeamcastPDF, leads: list):
    if not leads:
        return
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(180, 83, 9)
    pdf.cell(0, 7, f"Review Queue - {len(leads)} leads (score 4-5, needs your call)",
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(55, 65, 81)
    for lead in leads:
        contact = lead.get("contact", {})
        company = lead.get("company", {})
        scoring = lead.get("scoring", {})
        name = truncate(contact.get("full_name") or "Contact TBD", 30)
        title_str = truncate(contact.get("title") or "Unknown title", 40)
        co = truncate(company.get("name") or "Unknown company", 30)
        score = scoring.get("fit_score") or 0
        rationale = truncate(scoring.get("fit_rationale") or "", 110)
        pdf.cell(0, 5, f"- {name} | {title_str} @ {co}  |  Score: {score:.1f}",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        if rationale:
            pdf.set_font("Helvetica", "I", 8)
            pdf.set_text_color(107, 114, 128)
            pdf.cell(6, 4, "", new_x=XPos.RIGHT, new_y=YPos.TOP)
            pdf.cell(0, 4, rationale, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(55, 65, 81)
    pdf.ln(4)


def load_stats(leads: list) -> dict:
    qualified = [l for l in leads if l.get("status") in ("priority", "good")]
    review = [l for l in leads if l.get("status") == "hold"]
    discarded = [l for l in leads if l.get("status") == "discard"]
    by_source: dict = {}
    for l in leads:
        src = l.get("source", "unknown")
        by_source[src] = by_source.get(src, 0) + 1
    run_ids = list({l.get("run_id") for l in leads if l.get("run_id")})
    return {
        "total_sourced": len(leads),
        "after_dedup": len(leads),
        "qualified": len(qualified),
        "review_queue": len(review),
        "discarded": len(discarded),
        "by_source": by_source,
        "run_id": run_ids[0] if run_ids else "unknown",
    }


def main():
    parser = argparse.ArgumentParser(description="Generate Teamcast PDF lead report")
    parser.add_argument("--input", default=str(DEFAULT_INPUT), help="Path to leads.json")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Output PDF path")
    parser.add_argument("--run-id", help="Override run ID shown in header")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_path = Path(args.output)

    with open(input_path) as f:
        all_leads = json.load(f)
    if not isinstance(all_leads, list):
        all_leads = []

    stats = load_stats(all_leads)
    run_id = args.run_id or stats["run_id"]
    date_str = datetime.now().strftime("%B %d, %Y")

    priority_leads = sorted(
        [l for l in all_leads if l.get("status") == "priority"],
        key=lambda l: l.get("scoring", {}).get("fit_score") or 0,
        reverse=True,
    )
    good_leads = sorted(
        [l for l in all_leads if l.get("status") == "good"],
        key=lambda l: l.get("scoring", {}).get("fit_score") or 0,
        reverse=True,
    )
    hold_leads = [l for l in all_leads if l.get("status") == "hold"]

    pdf = TeamcastPDF(run_id=run_id, date_str=date_str)
    pdf.add_page()
    render_summary(pdf, {**stats, "run_id": run_id})

    pdf.add_page()
    render_leads_section(pdf, priority_leads, f"Priority Leads ({len(priority_leads)}) - Score 8-10", (220, 38, 38))
    render_leads_section(pdf, good_leads, f"Good Leads ({len(good_leads)}) - Score 6-7", (37, 99, 235))
    render_review_queue(pdf, hold_leads)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(output_path))
    print(f"PDF report written to {output_path}  ({len(priority_leads)+len(good_leads)} qualified leads)")


if __name__ == "__main__":
    main()
